<a href="https://colab.research.google.com/github/wangbxj1234/data_process_trick/blob/main/sort_matirx_and_cut_off.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
k_weights=np.array([[3,2,1],[6,5,4]])

kernel_weights = np.copy(k_weights)
ind = np.unravel_index(
        np.argsort(
            np.abs(kernel_weights),
            axis=None),
        kernel_weights.shape)

In [12]:
print(np.argsort(np.abs(kernel_weights),axis=None))#After sorting, it becomes a one-dimensional array, and the position information becomes an integer.

[2 1 0 5 4 3]


In [13]:
print(ind)#unravel_index ：Get the position information from the 1-dimensional array while keep the order

(array([0, 0, 0, 1, 1, 1]), array([2, 1, 0, 2, 1, 0]))


In [16]:
cutoff = int(len(ind[0])*0.8)

sparse_cutoff_inds = (ind[0][0:cutoff], ind[1][0:cutoff])#position information of the index with the smallest weight according to the dimension,(0,2),(0,1),(0,0),(1,2)...
kernel_weights[sparse_cutoff_inds] = 0.#cut off
print(kernel_weights)     

[[0 0 0]
 [6 5 0]]
